import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile, readdir, unlink } from "node:fs/promises";
import path from "node:path";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import * as icons from "@phosphor-icons/react/dist/ssr";
import {
  assets,
  offers,
  archivedOffers,
  directoryAssets,
} from "../lib/catalog";
import { toCardAsset } from "../lib/catalog-card";
import type { Icon, IconWeight } from "@phosphor-icons/react";

const root = process.cwd();
const generated = path.join(root, "lib", "generated");
const staticRoot = path.join(root, "public", "_catalog");
const uiRoot = path.join(root, "public", "_ui");
const digest = (content: string) =>
  createHash("sha256").update(content).digest("hex").slice(0, 16);

async function writeStable(file: string, content: string) {
  if ((await readFile(file, "utf8").catch(() => null)) !== content)
    await writeFile(file, content);
}
async function cleanGeneratedFiles(directory: string, keep: string) {
  // These directories contain only our generated indexes/sprite, never previews.
  const resolved = path.resolve(directory);
  if (![staticRoot, uiRoot].includes(resolved))
    throw new Error("Unexpected generated directory");
  for (const item of await readdir(resolved, { withFileTypes: true })) {
    if (
      item.isFile() &&
      /^(index-[a-f0-9]+\.json|icons-[a-f0-9]+\.svg)$/.test(item.name) &&
      item.name !== keep
    ) {
      await unlink(path.join(resolved, item.name));
    }
  }
}
async function main() {
  await Promise.all(
    [generated, staticRoot, uiRoot].map((directory) =>
      mkdir(directory, { recursive: true }),
    ),
  );
  const catalog = JSON.stringify({
    version: 1,
    assets: [
      ...assets,
      ...offers,
      ...archivedOffers.map((item) => item.offer),
    ].map(toCardAsset),
    archivedIds: archivedOffers.map((item) => item.offer.id),
  });
  const indexName = `index-${digest(catalog)}.json`;
  await writeStable(path.join(staticRoot, indexName), catalog);
  await writeStable(
    path.join(generated, "catalog.ts"),
    `// Generated by scripts/prepare-static.ts; do not edit.\nexport const catalogIndexUrl = ${JSON.stringify(`/_catalog/${indexName}`)};\n` +
      `export const catalogIds: string[] = ${JSON.stringify(directoryAssets.map((asset) => asset.id))};\n`,
  );
  await cleanGeneratedFiles(staticRoot, indexName);

  const source = await readFile(path.join(root, "lib", "icons.tsx"), "utf8");
  const names = [...source.matchAll(/createIcon\(\s*"(\w+)"\s*,?\s*\)/g)].map(
    (match) => match[1],
  );
  const weights: IconWeight[] = [
    "regular",
    "thin",
    "light",
    "bold",
    "fill",
    "duotone",
  ];
  const symbols: string[] = [];
  for (const name of names) {
    const IconComponent = icons[name as keyof typeof icons] as Icon;
    if (!IconComponent) throw new Error(`Unknown UI icon: ${name}`);
    for (const weight of weights) {
      const markup = renderToStaticMarkup(
        createElement(IconComponent, { weight }),
      );
      const body = markup.slice(
        markup.indexOf(">") + 1,
        markup.lastIndexOf("</svg>"),
      );
      symbols.push(
        `<symbol id="${name}-${weight}" viewBox="0 0 256 256">${body}</symbol>`,
      );
    }
  }
  const license = await readFile(
    path.join(root, "node_modules", "@phosphor-icons", "react", "LICENSE"),
    "utf8",
  );
  const sprite = `<svg xmlns="http://www.w3.org/2000/svg"><!-- ${license.replaceAll("--", "—")} -->${symbols.join("")}</svg>`;
  const spriteName = `icons-${digest(sprite)}.svg`;
  await writeStable(path.join(uiRoot, spriteName), sprite);
  await writeStable(
    path.join(generated, "icons.ts"),
    `// Generated by scripts/prepare-static.ts; do not edit.\nexport const iconSpriteUrl = ${JSON.stringify(`/_ui/${spriteName}`)};\n`,
  );
  await cleanGeneratedFiles(uiRoot, spriteName);
  console.log(
    `Static discovery prepared: ${directoryAssets.length} assets, ${(Buffer.byteLength(catalog) / 1000000).toFixed(2)} MB shared index, ${names.length} shared UI icons.`,
  );
}
void main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
